#!/usr/bin/env bash

usage() {
  echo "Usage: $(basename $0) sequences.fa" 1>&2
  echo "" 1>&2
  echo "" 1>&2
  exit 1
}

################################
### PARSE COMMAND LINE ARGS ####
################################

while getopts ":i:t:a:k:m:f:s:l:x:p:o:" opt; do
  case $opt in
  t)
   NTHREADS=$OPTARG
   ;;
  a)
   MAXAT=$OPTARG
   ;;
  k)
   K=$OPTARG
   ;;
  m)
   MINMEDIAN=$OPTARG
   ;;
  f)
   FIRSTK=$OPTARG
   ;;
  s)
   HASHSIZE=$OPTARG
   ;;
  l)
   MINREADLENGTH=$OPTARG
   ;;
  x)
   MAXREADLENGTH=$OPTARG
   ;;
  p)
   OUTPDF=$OPTARG
   ;;
  o)
   OUTFASTA=$OPTARG
   ;;
  \?)
   echo "Invalid option: -$OPTARG" >&2
   usage
   ;;
  [?])
   usage
   ;;
  :)
   echo "Option -$OPTARG requires an argument." >&2
   echo "" >&2
   usage
   ;;
  esac
done

shift $((OPTIND-1))

if [ -z $NTHREADS ]; then
  NTHREADS=1
fi

if [ -z $MAXAT ]; then
  MAXAT=0.7
fi

if [ -z $K ]; then
  K=10
fi

if [ -z $MINMEDIAN ]; then
  MINMEDIAN=5
fi

if [ -z $FIRSTK ]; then
  FIRSTK=10
fi

if [ -z $HASHSIZE ]; then
  HASHSIZE=100000
fi

if [ -z $MINREADLENGTH ]; then
  MINREADLENGTH=1000
fi

if [ -z $MAXREADLENGTH ]; then
  MAXREADLENGTH=1000000
fi

if [ -z $OUTFASTA ]; then
  2>&1 echo "must define output fasta"
  exit 1
fi

if [[ -z $@ ]]; then
  INPUT=$(cat /dev/stdin)
else
  INPUT=$@
fi

# check if jellyfish2 is in $PATH
jellyfish --version 2>/dev/null | grep "jellyfish 2" > /dev/null
LAC=$?
if [ $LAC -gt 0 ]; then
  2>&1 echo "jellyfish 2 not found in $PATH"
  exit 1
fi

# check if jellyfish2 is in $PATH
yass --version 2>&1 | grep "version 1" > /dev/null
LAC=$?
if [ $LAC -gt 0 ]; then
  2>&1 echo "yass not found in $PATH"
  exit 1
fi

>&2 echo "filtering sequences into $OUTFASTA"

while IFS=$'\t' read -r name sequence; do
  echo -e "${name}\n${sequence}" | \
  jellyfish count --disk -o /dev/stdout -L 2 --text -s $HASHSIZE -m $K /dev/stdin | \
  tail -n+2 | sort -k2,2nr | \
  awk -v k=$K -v maxAT=$MAXAT -v topkmers=$FIRSTK -v filename=$name -v sequence=$sequence -v minmedian=$MINMEDIAN '{
    a=gsub("A","A",$1);b=gsub("T","T",$1)
    if(((a+b)/k) < maxAT){
      goodkmers+=1
    }
    if(goodkmers==int(topkmers/2) && $2>=minmedian){
      print filename"\n"sequence; exit
    }
  }' &

  [ $( jobs | wc -l ) -ge $NTHREADS ] && wait
done < <(
  awk '{
    if($1~">"){
      print "~"$0"<"
    }else{
      print $0
    }
  }' $INPUT | \
  tr -d '\n' | \
  tr '~' '\n' | \
  tr '<' '\t' | \
  awk -v minl=$MINREADLENGTH -v maxl=$MAXREADLENGTH '{l=length($2);if(l>=minl && l<=maxl){print $1,$2}}' OFS='\t'
) > $OUTFASTA

>&2 echo "plotting self-alignments"
tmpfile=$(tempfile)
while IFS=$'\t' read -r name sequence; do

  counts=$(echo -e "${name}\n${sequence}" | \
  jellyfish count --disk -o /dev/stdout -L 2 --text -s $HASHSIZE -m $K /dev/stdin | \
  tail -n+2 | sort -k2,2nr | tr '\n' ';')
  
  echo -e "$name\n$sequence" > $tmpfile
  
  yass -d 3 $tmpfile $tmpfile 2>/dev/null | awk -v sequence=$sequence -v seqname=$name -v counts=$counts '{print $0,seqname,counts}' OFS='\t' | tail -n+2
  
  rm $tmpfile
done < <( cat $OUTFASTA | paste - - ) > ${OUTFASTA}.yass

kplot ${OUTFASTA}.yass



